{% set name = "rst2ansi" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rst2ansi-{{ version }}.tar.gz
  sha256: 1b17fb9a628d40f57933ad1a3aa952346444be069469508e73e95060da33fe6f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - docutils >=0.12

test:
  imports:
    - rst2ansi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Snaipe/python-rst-to-ansi
  summary: A rst converter to ansi-decorated console output
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - freundTech
